<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['vnpay'] = array (
    'vnpay_url' => 'http://sandbox.vnpayment.vn/paymentv2/vpcpay.html',
    'vnpay_code' => 'ICTLIFE1',
    'vnpay_secret_key' => 'ISDFGWJZVJFABUMZYKDFOSYWHHYNAPFS',
    'vnpay_secure_hash_type' => 'SHA256',
    'vnpay_order_type' => '190002',
    'vnpay_currency_code' => 'VND',
    'vnpay_return_url' => ($_SERVER['SERVER_NAME'] == 'localhost') ? 'http://xxx/vnpay-return-url.html' : 'https://xxx/vnpay-return-url.html',
    'vnpay_ipn_url' => 'https://xxx/vnpay-ipn-result.html',
);

/**
 * Danh sách các ngân hàng, ví điện tử mà VNPAY kết nối
 * Cập nhật lần cuối: 09/02/2021
 */
$config['vnpay_bank_list'] = array (
    array(
        'id' => 1,
        'code' => 'ABBANK',
        'name' => 'Ngân hàng thương mại cổ phần An Bình (ABBANK)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/abbank_logo.png'),
    array(
        'id' => 2,
        'code' => 'ACB',
        'name' => 'Ngân hàng ACB',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/acb_logo.png'),
    array(
        'id' => 3,
        'code' => 'AGRIBANK',
        'name' => 'Ngân hàng Nông nghiệp (Agribank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/agribank_logo.png'),
    array(
        'id' => 4,
        'code' => 'BACABANK',
        'name' => 'Ngân Hàng TMCP Bắc Á',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/bacabank_logo.png'),
    array(
        'id' => 5,
        'code' => 'BIDV',
        'name' => 'Ngân hàng đầu tư và phát triển Việt Nam (BIDV)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/bidv_logo.png'),
    array(
        'id' => 6,
        'code' => 'DONGABANK',
        'name' => 'Ngân hàng Đông Á (DongABank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/dongabank_logo.png'),
    array(
        'id' => 7,
        'code' => 'EXIMBANK',
        'name' => 'Ngân hàng EximBank',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/eximbank_logo.png'),
    array(
        'id' => 8,
        'code' => 'HDBANK',
        'name' => 'Ngan hàng HDBank',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/hdbank_logo.png'),
    array(
        'id' => 9,
        'code' => 'IVB',
        'name' => 'Ngân hàng TNHH Indovina (IVB)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/ivb_logo.png'),
    array(
        'id' => 10,
        'code' => 'MBBANK',
        'name' => 'Ngân hàng thương mại cổ phần Quân đội',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/mbbank_logo.png'),
    array(
        'id' => 11,
        'code' => 'MSBANK',
        'name' => 'Ngân hàng Hàng Hải (MSBANK)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/msbank_logo.png'),
    array(
        'id' => 12,
        'code' => 'NAMABANK',
        'name' => 'Ngân hàng Nam Á (NamABank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/namabank_logo.png'),
    array(
        'id' => 13,
        'code' => 'NCB',
        'name' => 'Ngân hàng Quốc dân (NCB)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/ncb_logo.png'),
    array(
        'id' => 14,
        'code' => 'OCB',
        'name' => 'Ngân hàng Phương Đông (OCB)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/ocb_logo.png'),
    array(
        'id' => 15,
        'code' => 'OJB',
        'name' => 'Ngân hàng Đại Dương (OceanBank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/ojb_logo.png'),
    array(
        'id' => 16,
        'code' => 'PVCOMBANK',
        'name' => 'Ngân hàng TMCP Đại Chúng Việt Nam',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/PVComBank_logo.png'),
    array(
        'id' => 17,
        'code' => 'SACOMBANK',
        'name' => 'Ngân hàng TMCP Sài Gòn Thương Tín (SacomBank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/sacombank_logo.png'),
    array(
        'id' => 18,
        'code' => 'SAIGONBANK',
        'name' => 'Ngân hàng thương mại cổ phần Sài Gòn Công Thương',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/saigonbank.png'),
    array(
        'id' => 19,
        'code' => 'SCB',
        'name' => 'Ngân hàng TMCP Sài Gòn (SCB)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/scb_logo.png'),
    array(
        'id' => 20,
        'code' => 'SHB',
        'name' => 'Ngân hàng Thương mại cổ phần Sài Gòn - Hà Nội(SHB)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/shb_logo.png'),
    array(
        'id' => 21,
        'code' => 'TECHCOMBANK',
        'name' => 'Ngân hàng Kỹ thương Việt Nam (TechcomBank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/techcombank_logo.png'),
    array(
        'id' => 22,
        'code' => 'TPBANK',
        'name' => 'Ngân hàng Tiên Phong (TPBank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/tpbank_logo.png'),
    array(
        'id' => 23,
        'code' => 'VPBANK',
        'name' => 'Ngân hàng Việt Nam Thịnh vượng (VPBank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vpbank_logo.png'),
    array(
        'id' => 24,
        'code' => 'SEABANK',
        'name' => 'Ngân Hàng TMCP Đông Nam Á',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/seabank_logo.png'),
    array(
        'id' => 25,
        'code' => 'VIB',
        'name' => 'Ngân hàng Thương mại cổ phần Quốc tế Việt Nam (VIB)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vib_logo.png'),
    array(
        'id' => 26,
        'code' => 'VIETABANK',
        'name' => 'Ngân hàng TMCP Việt Á',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vietabank_logo.png'),
    array(
        'id' => 27,
        'code' => 'VIETBANK',
        'name' => 'Ngân hàng thương mại cổ phần Việt Nam Thương Tín',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vietabank_logo.png'),
    array(
        'id' => 28,
        'code' => 'VIETCAPITALBANK',
        'name' => 'Ngân Hàng Bản Việt',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vccb_logo.png'),
    array(
        'id' => 29,
        'code' => 'VIETCOMBANK',
        'name' => 'Ngân hàng Ngoại thương (Vietcombank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vietcombank_logo.png'),
    array(
        'id' => 30,
        'code' => 'VIETINBANK',
        'name' => 'Ngân hàng Công thương (Vietinbank)',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vietinbank_logo.png'),
    array(
        'id' => 31,
        'code' => 'BIDC',
        'name' => 'Ngân Hàng BIDC',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/bidc_logo.png'),
    array(
        'id' => 32,
        'code' => 'LAOVIETBANK',
        'name' => 'NGÂN HÀNG LIÊN DOANH LÀO - VIỆT',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/laovietbank_logo.png'),
    array(
        'id' => 33,
        'code' => 'WOORIBANK',
        'name' => 'Ngân hàng TNHH MTV Woori Việt Nam',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/woori_logo.png'),
    array(
        'id' => 34,
        'code' => 'AMEX',
        'name' => 'American Express',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/amex_logo.png'),
    array(
        'id' => 35,
        'code' => 'VISA',
        'name' => 'Thẻ quốc tế Visa',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/visa_logo.png'),
    array(
        'id' => 36,
        'code' => 'MASTERCARD',
        'name' => 'Thẻ quốc tế MasterCard',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/mastercard_logo.png'),
    array(
        'id' => 37,
        'code' => 'JCB',
        'name' => 'Thẻ quốc tế JCB',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/jcb_logo.png'),
    array(
        'id' => 38,
        'code' => 'UPI',
        'name' => 'UnionPay International',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/upi_logo.png'),
    array(
        'id' => 39,
        'code' => 'VNMART',
        'name' => 'Ví điện tử VnMart',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vnmart_logo.png'),
    array(
        'id' => 40,
        'code' => 'VNPAYQR',
        'name' => 'Cổng thanh toán VNPAYQR',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/CTT-VNPAY-QR.png'),
    array(
        'id' => 41,
        'code' => '1PAY',
        'name' => 'Ví điện tử 1Pay',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/1pay_logo.png'),
    array(
        'id' => 42,
        'code' => 'FOXPAY',
        'name' => 'Ví điện tử FOXPAY',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/foxpay_logo.png'),
    array(
        'id' => 43,
        'code' => 'VIMASS',
        'name' => 'Ví điện tử Vimass',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vimass_logo.png'),
    array(
        'id' => 44,
        'code' => 'VINID',
        'name' => 'Ví điện tử VINID',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vinid_logo.png'),
    array(
        'id' => 45,
        'code' => 'VIVIET',
        'name' => 'Ví điện tử Ví Việt',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/viviet_logo.png'),
    array(
        'id' => 46,
        'code' => 'VNPTPAY',
        'name' => 'Ví điện tử VNPTPAY',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/vnptpay_logo.png'),
    array(
        'id' => 47,
        'code' => 'YOLO',
        'name' => 'Ví điện tử YOLO',
        'logo' => 'https://sandbox.vnpayment.vn/apis/assets/images/bank/yolo_logo.png')
);

/**
 * Danh sách loại hàng hóa
 * Cập nhật lần cuối: 09/02/2021
 */
$config['vnpay_order_type'] = array (
    array('id' => 1, 'code' => '100000', 'name' => 'Thực Phẩm - Tiêu Dùng'),
    array('id' => 2, 'code' => '100001', 'name' => 'Bánh kẹo - Đồ ăn vặt - Giải khát'),
    array('id' => 3, 'code' => '100003', 'name' => 'Thực phẩm khô'),
    array('id' => 4, 'code' => '100004', 'name' => 'Sữa - Kem & sản phẩm từ sữa'),
    array('id' => 5, 'code' => '100005', 'name' => 'Hóa phẩm – chất tẩy'),
    array('id' => 6, 'code' => '110000', 'name' => 'Điện thoại - Máy tính bảng'),
    array('id' => 7, 'code' => '110001', 'name' => 'Điện thoại dị động'),
    array('id' => 8, 'code' => '110002', 'name' => 'Máy tính bảng'),
    array('id' => 9, 'code' => '110003', 'name' => 'Smart Watch'),
    array('id' => 10, 'code' => '110004', 'name' => 'Phụ kiện'),
    array('id' => 11, 'code' => '110005', 'name' => 'Sim/Thẻ'),
    array('id' => 12, 'code' => '120000', 'name' => 'Điện gia dụng'),
    array('id' => 13, 'code' => '120001', 'name' => 'Điện gia dụng nhà bếp'),
    array('id' => 14, 'code' => '120002', 'name' => 'Điện gia dụng gia đình'),
    array('id' => 15, 'code' => '120003', 'name' => 'Điện lạnh & Điện cỡ lớn'),
    array('id' => 16, 'code' => '130000', 'name' => 'Máy tính - Thiết bị văn phòng'),
    array('id' => 17, 'code' => '130001', 'name' => 'Máy tính xách tay'),
    array('id' => 18, 'code' => '130002', 'name' => 'Máy tính để bàn'),
    array('id' => 19, 'code' => '130003', 'name' => 'Màn hình máy tính'),
    array('id' => 20, 'code' => '130004', 'name' => 'Thiết bị mạng'),
    array('id' => 21, 'code' => '130005', 'name' => 'Phần mềm'),
    array('id' => 22, 'code' => '130006', 'name' => 'Linh kiện, Phụ kiện'),
    array('id' => 23, 'code' => '130007', 'name' => 'Máy in'),
    array('id' => 24, 'code' => '130008', 'name' => 'Thiết bị văn phòng khác'),
    array('id' => 25, 'code' => '140000', 'name' => 'Điện tử - Âm thanh'),
    array('id' => 26, 'code' => '140001', 'name' => 'Tivi'),
    array('id' => 27, 'code' => '140002', 'name' => 'Loa'),
    array('id' => 28, 'code' => '140003', 'name' => 'Dàn âm thanh'),
    array('id' => 29, 'code' => '140004', 'name' => 'Đồ chơi công nghệ'),
    array('id' => 30, 'code' => '140005', 'name' => 'Thiết bị Kỹ thuật số'),
    array('id' => 31, 'code' => '150000', 'name' => 'Sách/Báo/Tạp chí'),
    array('id' => 32, 'code' => '150001', 'name' => 'Văn phòng phẩm'),
    array('id' => 33, 'code' => '150002', 'name' => 'Quà tặng'),
    array('id' => 34, 'code' => '150003', 'name' => 'Nhạc cụ'),
    array('id' => 35, 'code' => '160000', 'name' => 'Thể thao, dã ngoại'),
    array('id' => 36, 'code' => '160001', 'name' => 'Trang phục thể thao'),
    array('id' => 37, 'code' => '160002', 'name' => 'Phụ kiện thể thao'),
    array('id' => 38, 'code' => '160003', 'name' => 'Đồ tập Yoga, thể hình'),
    array('id' => 39, 'code' => '160004', 'name' => 'Đồ/Vật dụng Dã ngoại'),
    array('id' => 40, 'code' => '170000', 'name' => 'Khách sạn & Du lịch'),
    array('id' => 41, 'code' => '170001', 'name' => 'Du lịch trong nước'),
    array('id' => 42, 'code' => '170002', 'name' => 'Du lịch nước ngoài'),
    array('id' => 43, 'code' => '170003', 'name' => 'Đặt phòng khách sạn'),
    array('id' => 44, 'code' => '180000', 'name' => 'Ẩm thực'),
    array('id' => 45, 'code' => '190000', 'name' => 'Giải trí & Đào tạo'),
    array('id' => 46, 'code' => '190001', 'name' => 'Vé xem phim'),
    array('id' => 47, 'code' => '190002', 'name' => 'Thẻ học/ Học trực tuyến'),
    array('id' => 48, 'code' => '190003', 'name' => 'Giải trí, vui chơi khác'),
    array('id' => 49, 'code' => '190004', 'name' => 'Thẻ học trực tuyến/Thẻ hội viên'),
    array('id' => 50, 'code' => '200000', 'name' => 'Thời trang'),
    array('id' => 51, 'code' => '200001', 'name' => 'Thời trang nữ'),
    array('id' => 52, 'code' => '200002', 'name' => 'Phụ kiện Nữ'),
    array('id' => 53, 'code' => '200003', 'name' => 'Thời trang Nam'),
    array('id' => 54, 'code' => '200004', 'name' => 'Thời trang Trẻ Em'),
    array('id' => 55, 'code' => '210000', 'name' => 'Sức khỏe - Làm đẹp'),
    array('id' => 56, 'code' => '210001', 'name' => 'Kem chống nắng'),
    array('id' => 57, 'code' => '210002', 'name' => 'Chăm sóc da mặt'),
    array('id' => 58, 'code' => '210003', 'name' => 'Trang điểm'),
    array('id' => 59, 'code' => '210004', 'name' => 'Chăm sóc cá nhân'),
    array('id' => 60, 'code' => '220000', 'name' => 'Mẹ & Bé'),
    array('id' => 61, 'code' => '220001', 'name' => 'Sữa & Bột cho bé'),
    array('id' => 62, 'code' => '220002', 'name' => 'Vệ sinh chăm sóc cho bé'),
    array('id' => 63, 'code' => '220003', 'name' => 'Đồ chơi & Đồ dùng trẻ em'),
    array('id' => 64, 'code' => '220004', 'name' => 'Đồ dùng ăn uống cho bé'),
    array('id' => 65, 'code' => '230000', 'name' => 'Vật dụng nhà bếp'),
    array('id' => 66, 'code' => '230001', 'name' => 'Nội thất'),
    array('id' => 67, 'code' => '240000', 'name' => 'Xe cộ - phương tiện'),
    array('id' => 68, 'code' => '240001', 'name' => 'Mô tô - Xe máy'),
    array('id' => 69, 'code' => '240002', 'name' => 'Phụ kiện xe máy'),
    array('id' => 70, 'code' => '240003', 'name' => 'Phụ kiện ô tô'),
    array('id' => 71, 'code' => '240004', 'name' => 'Xe đạp điện'),
    array('id' => 72, 'code' => '250000', 'name' => 'Thanh toán hóa đơn'),
    array('id' => 73, 'code' => '250001', 'name' => 'Hóa đơn tiền điện'),
    array('id' => 74, 'code' => '250002', 'name' => 'Hóa đơn tiền nước'),
    array('id' => 75, 'code' => '250003', 'name' => 'Hóa đơn điện thoại trả sau'),
    array('id' => 76, 'code' => '250004', 'name' => 'Hóa đơn ADSL'),
    array('id' => 77, 'code' => '250005', 'name' => 'Hóa đơn truyền hình cáp'),
    array('id' => 78, 'code' => '250006', 'name' => 'Hóa đơn dịch vụ'),
    array('id' => 79, 'code' => '250007', 'name' => 'Vé máy bay'),
    array('id' => 80, 'code' => '260000', 'name' => 'Mua mã thẻ'),
    array('id' => 81, 'code' => '260001', 'name' => 'Thẻ điện thoại'),
    array('id' => 82, 'code' => '260002', 'name' => 'Thẻ Game'),
    array('id' => 83, 'code' => '270000', 'name' => 'Nhà thuốc - Dịch vụ y tế'),
    array('id' => 84, 'code' => '270001', 'name' => 'Đăng ký khám/chữa bệnh')
);
